# .streamlit/config.toml
[server]
runOnSave = true
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base="light"
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"

